package test;

import net.drools.bean.*;
import java.util.List;

//global String[] orderNames;
query "query fact count"
    Customer();
end

//规则rule1的注释
/*
规则rule1的注释
这是一个测试用例
*/
rule "rule1"
    //salience 2
    //no-loop true
    //date-effective "2014-08-23"
    //date-expires "2014-08-25"
    //activation-group "test"
    //duration 3000
    agenda-group "001"
    auto-focus true
    when
        //$order:Order(items not contains "手机");
        //$customer:Customer(age > 20, orders contains $order);
        //$order:Order(name memberOf orderNames)
        //$orderList:String[]();
        //$order:Order(name not memberOf $orderList)
        //$customer:Customer(name not matches "李.*")
        //eval(true);
        //$customer:Customer(name == "张三", age == 20);
        //$customer:Customer(name == "张三")
        eval(true)   #没有条件判断
    then
        //System.out.println($customer.getName());
        //System.out.println($order.getName());
        //System.out.println($order.getName());
        //System.out.println($customer.getName());
        //Customer cus = new Customer();
        //cus.setName("张三");
        //cus.setAge(1);
        //insert(cus);
        //System.out.println("modify before customer id: " + $customer.getId()+";age: "+$customer.getAge());
        //modify($customer){
        //    setId("super man"),
        //    setAge(30)
        //}
        //update($customer)
        //System.out.println("customer name: " + $customer.getName());
        //System.out.println("rule1 is execution!");
        //System.out.println("dialect: " + drools.getRule().getDialect());
        //System.out.println("rule thread id: " + Thread.currentThread().getId());
        System.out.println("rule1 execute");
end
rule "rule2"
    //salience 1
    //no-loop true
    //activation-group "test"
    agenda-group "002"
    auto-focus true
    when
        //$customer:Customer(name == "张三",age < 10);
        //$customer:Customer(name == "张三");
        eval(true)
    then
        //System.out.println("rule2---"+$customer.getName());
        //Customer customer = new Customer();
        //customer.setName("张三");
        //customer.setAge($customer.getAge() + 1);
        ////update($customer);
        //update(drools.getWorkingMemory().getFactHandleByIdentity($customer), customer);
        //System.out.println("----------" + $customer.getName());
        //retract($customer)
        //System.out.println("modify after customer id: " + $customer.getId() + ";age: " + $customer.getAge());
        System.out.println("rule2 execute");
end
